server:
  port: 8081
  servlet:
    context-path:
spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  datasource:
    name: mywebpage
    url: jdbc:mysql://localhost:3306/mywebpage?serverTimezone=UTC   #??mysql8.0?????????
    username: root
    password: azsx18327946
    driver-class-name: com.mysql.cj.jdbc.Driver  #???????
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:Dao/*.xml  #??????
  type-aliases-package: com.example.mywebpage.bean #?????
logging:
  level:
    com.example.mywebpage.dao: DEBUG